'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'このソース コードは Microsoft.VSDesigner、バージョン 1.1.4322.2407 によって自動生成されました。
'
Namespace is2init
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://Walkthrough/XmlWebServices/")>  _
    Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://wwwis2.fukutsu.co.jp/is2/is2init/Service1.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Set_tanmatsu", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Set_tanmatsu(ByVal sUser() As String, ByVal sKey() As String) As String()
            Dim results() As Object = Me.Invoke("Set_tanmatsu", New Object() {sUser, sKey})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginSet_tanmatsu(ByVal sUser() As String, ByVal sKey() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Set_tanmatsu", New Object() {sUser, sKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSet_tanmatsu(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_tanmatsu", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Upd_tanmatsu(ByVal sUser() As String, ByVal sKey() As String) As String
            Dim results() As Object = Me.Invoke("Upd_tanmatsu", New Object() {sUser, sKey})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginUpd_tanmatsu(ByVal sUser() As String, ByVal sKey() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Upd_tanmatsu", New Object() {sUser, sKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpd_tanmatsu(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_riyou", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Upd_riyou(ByVal sUser() As String, ByVal sKey() As String) As String
            Dim results() As Object = Me.Invoke("Upd_riyou", New Object() {sUser, sKey})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginUpd_riyou(ByVal sUser() As String, ByVal sKey() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Upd_riyou", New Object() {sUser, sKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpd_riyou(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_tanmatsu2", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_tanmatsu2(ByVal sUser() As String, ByVal sKey1 As String) As String()
            Dim results() As Object = Me.Invoke("Get_tanmatsu2", New Object() {sUser, sKey1})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_tanmatsu2(ByVal sUser() As String, ByVal sKey1 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_tanmatsu2", New Object() {sUser, sKey1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_tanmatsu2(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_tanmatsu3", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_tanmatsu3(ByVal sUser() As String, ByVal sKey1() As String) As String()
            Dim results() As Object = Me.Invoke("Get_tanmatsu3", New Object() {sUser, sKey1})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_tanmatsu3(ByVal sUser() As String, ByVal sKey1() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_tanmatsu3", New Object() {sUser, sKey1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_tanmatsu3(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_riyou", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_riyou(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String) As String()
            Dim results() As Object = Me.Invoke("Get_riyou", New Object() {sUser, sKey1, sKey2})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_riyou(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_riyou", New Object() {sUser, sKey1, sKey2}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_riyou(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_seikyu", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_seikyu(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String) As String()
            Dim results() As Object = Me.Invoke("Get_seikyu", New Object() {sUser, sKey1, sKey2})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_seikyu(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_seikyu", New Object() {sUser, sKey1, sKey2}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_seikyu(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/login", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function login(ByVal sUser() As String, ByVal sKey() As String) As String()
            Dim results() As Object = Me.Invoke("login", New Object() {sUser, sKey})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function Beginlogin(ByVal sUser() As String, ByVal sKey() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("login", New Object() {sUser, sKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endlogin(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_jyotai", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_jyotai(ByVal sUser() As String) As String()
            Dim results() As Object = Me.Invoke("Get_jyotai", New Object() {sUser})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_jyotai(ByVal sUser() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_jyotai", New Object() {sUser}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_jyotai(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_syukabi", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_syukabi(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String) As String()
            Dim results() As Object = Me.Invoke("Get_syukabi", New Object() {sUser, sKey1, sKey2})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_syukabi(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_syukabi", New Object() {sUser, sKey1, sKey2}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_syukabi(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_bumon", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_bumon(ByVal sUser() As String, ByVal sKey1 As String) As String()
            Dim results() As Object = Me.Invoke("Get_bumon", New Object() {sUser, sKey1})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_bumon(ByVal sUser() As String, ByVal sKey1 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_bumon", New Object() {sUser, sKey1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_bumon(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_message", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_message(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String) As String()
            Dim results() As Object = Me.Invoke("Get_message", New Object() {sUser, sKey1, sKey2})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_message(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_message", New Object() {sUser, sKey1, sKey2}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_message(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_seigyo", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_seigyo(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String) As String()
            Dim results() As Object = Me.Invoke("Get_seigyo", New Object() {sUser, sKey1, sKey2})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_seigyo(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_seigyo", New Object() {sUser, sKey1, sKey2}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_seigyo(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_seigyo2", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_seigyo2(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String, ByVal iLength As Integer) As String()
            Dim results() As Object = Me.Invoke("Get_seigyo2", New Object() {sUser, sKey1, sKey2, iLength})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_seigyo2(ByVal sUser() As String, ByVal sKey1 As String, ByVal sKey2 As String, ByVal iLength As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_seigyo2", New Object() {sUser, sKey1, sKey2, iLength}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_seigyo2(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Ins_seigyo", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Ins_seigyo(ByVal sUser() As String, ByVal sKey() As String) As String
            Dim results() As Object = Me.Invoke("Ins_seigyo", New Object() {sUser, sKey})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginIns_seigyo(ByVal sUser() As String, ByVal sKey() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Ins_seigyo", New Object() {sUser, sKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndIns_seigyo(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_seigyo", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Upd_seigyo(ByVal sUser() As String, ByVal sKey() As String) As String
            Dim results() As Object = Me.Invoke("Upd_seigyo", New Object() {sUser, sKey})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginUpd_seigyo(ByVal sUser() As String, ByVal sKey() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Upd_seigyo", New Object() {sUser, sKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpd_seigyo(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/login2", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function login2(ByVal sUser() As String, ByVal sKey() As String) As String()
            Dim results() As Object = Me.Invoke("login2", New Object() {sUser, sKey})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function Beginlogin2(ByVal sUser() As String, ByVal sKey() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("login2", New Object() {sUser, sKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endlogin2(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_tanmatu", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Upd_tanmatu(ByVal sUser() As String, ByVal sKey As String) As String()
            Dim results() As Object = Me.Invoke("Upd_tanmatu", New Object() {sUser, sKey})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginUpd_tanmatu(ByVal sUser() As String, ByVal sKey As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Upd_tanmatu", New Object() {sUser, sKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpd_tanmatu(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/login3", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function login3(ByVal sUser() As String, ByVal sKey() As String) As String()
            Dim results() As Object = Me.Invoke("login3", New Object() {sUser, sKey})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function Beginlogin3(ByVal sUser() As String, ByVal sKey() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("login3", New Object() {sUser, sKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endlogin3(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_hatuten3", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_hatuten3(ByVal sUser() As String, ByVal sKcode As String, ByVal sBcode As String) As String()
            Dim results() As Object = Me.Invoke("Get_hatuten3", New Object() {sUser, sKcode, sBcode})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_hatuten3(ByVal sUser() As String, ByVal sKcode As String, ByVal sBcode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_hatuten3", New Object() {sUser, sKcode, sBcode}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_hatuten3(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_Kadobi", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_Kadobi(ByVal sUser() As String, ByVal sDateStart As String, ByVal sDateEnd As String) As String()
            Dim results() As Object = Me.Invoke("Get_Kadobi", New Object() {sUser, sDateStart, sDateEnd})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGet_Kadobi(ByVal sUser() As String, ByVal sDateStart As String, ByVal sDateEnd As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_Kadobi", New Object() {sUser, sDateStart, sDateEnd}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_Kadobi(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/wakeupDB", RequestNamespace:="http://Walkthrough/XmlWebServices/", ResponseNamespace:="http://Walkthrough/XmlWebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function wakeupDB() As String
            Dim results() As Object = Me.Invoke("wakeupDB", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginwakeupDB(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("wakeupDB", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndwakeupDB(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
